apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mysecret-sops
spec:
  secretTemplates:
    - name: secret-postgresuser
      labels:
        label1: label1-postgresuser
      annotations:
        key1: key1-postgresuser
      stringData:
        data-name0: userdemomanifest
      data:
        data-name1: userdemomanifest
    - name: secret-postgresuser
      labels:
        label1: label1-postgrespassword
      annotations:
        key1: key1-postgrespassword
      stringData:
        data-name0: "My$ecrETPAss0rd*"
      data:
        data-name1: "My$ecrETPAss0rd*"
 